# -*- coding: utf-8 -*-
"""
Created on Thu Nov 19 17:22:22 2020

@author: white
"""

# null words to ignore (prepositions, conjunctions etc..)

def ignore_these_words():

    prepositions = ["aboard", 
    "about", 
    "above", 
    "across", 
    "after", 
    "against", 
    "along", 
    "amid", 
    "among", 
    "anti", 
    "around", 
    "as", 
    "at", 
    "before", 
    "behind", 
    "below", 
    "beneath", 
    "beside", 
    "besides", 
    "between", 
    "beyond", 
    "but", 
    "by", 
    "concerning", 
    "considering", 
    "despite", 
    "down", 
    "during", 
    "except", 
    "excepting", 
    "excluding", 
    "following", 
    "for", 
    "from", 
    "in", 
    "inside", 
    "into", 
    "like", 
    "minus", 
    "near", 
    "of", 
    "off", 
    "on", 
    "onto", 
    "opposite", 
    "outside", 
    "over", 
    "past", 
    "per", 
    "plus", 
    "regarding", 
    "round", 
    "save", 
    "since", 
    "than", 
    "through", 
    "to", 
    "toward", 
    "towards", 
    "under", 
    "underneath", 
    "unlike", 
    "until", 
    "up", 
    "upon", 
    "versus", 
    "via", 
    "with", 
    "within", 
    "without",
    "at",
    "a",
    "the",
    "that",
    "this",
    "and",
    "but",
    "not",
    "it",
    "is"]

    return prepositions